#!/bin/bash

# RTSSP-SHP Setup and Configuration Script
# This script helps configure the protocol, clean artifacts, and regenerate certificates

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SERVER_DIR="$SCRIPT_DIR/hjStreamServer"
PROXY_DIR="$SCRIPT_DIR/hjUDPproxy"

echo "==============================================="
echo "  RTSSP & RTSSP-SHP Configuration Setup"
echo "==============================================="
echo ""

# Function to prompt user with yes/no
ask_yes_no() {
    local prompt="$1"
    local response
    read -p "$prompt (y/n): " response
    case "$response" in
        [yY][eE][sS]|[yY]) return 0 ;;
        *) return 1 ;;
    esac
}

# Function to read user input with default
read_input() {
    local prompt="$1"
    local default="$2"
    local response
    read -p "$prompt [$default]: " response
    echo "${response:-$default}"
}

# ===== PHASE 1: Clean up old files =====
echo "[PHASE 1] Cleanup"
echo "===================="

if ask_yes_no "Clean up .class files?"; then
    echo "Removing .class files..."
    find "$SERVER_DIR" -name "*.class" -delete
    find "$PROXY_DIR" -name "*.class" -delete
    echo "✓ .class files removed"
fi

if ask_yes_no "Clean up .cer certificate files?"; then
    echo "Removing .cer files..."
    rm -f "$SERVER_DIR"/*.cer "$PROXY_DIR"/*.cer
    echo "✓ .cer files removed"
fi

echo ""

# ===== PHASE 2: Configure protocol mode =====
echo "[PHASE 2] Protocol Configuration"
echo "=================================="

echo "Select protocol mode:"
echo "  1) RTSSP (Part 1 - Static random keys per session)"
echo "  2) RTSSP-SHP (Part 2 - Dynamic key negotiation)"
mode_choice=$(read_input "Choose (1 or 2)" "1")

case "$mode_choice" in
    1)
        MODE="RTSSP"
        echo "✓ Selected: RTSSP (Part 1)"
        ;;
    2)
        MODE="RTSSP-SHP"
        echo "✓ Selected: RTSSP-SHP (Part 2)"
        ;;
    *)
        echo "Invalid choice. Defaulting to RTSSP"
        MODE="RTSSP"
        ;;
esac

echo ""

# ===== PHASE 3: Configure cipher algorithms =====
echo "[PHASE 3] Cipher Configuration"
echo "==============================="

echo "Cipher Algorithms:"
echo "  1) AES/CTR/NoPadding (stream cipher)"
echo "  2) AES/GCM/NoPadding (authenticated encryption)"
cipher_choice=$(read_input "Choose cipher (1 or 2)" "1")

case "$cipher_choice" in
    1)
        CIPHER="AES/CTR/NoPadding"
        HMAC="HmacSHA256"
        echo "✓ Selected: AES/CTR with HMAC-SHA256"
        ;;
    2)
        CIPHER="AES/GCM/NoPadding"
        HMAC="HmacSHA256"
        echo "✓ Selected: AES/GCM with HMAC-SHA256"
        ;;
    *)
        CIPHER="AES/CTR/NoPadding"
        HMAC="HmacSHA256"
        echo "✓ Defaulting to AES/CTR with HMAC-SHA256"
        ;;
esac

echo ""

# ===== PHASE 4: Configure key sizes =====
echo "[PHASE 4] Key Size Configuration"
echo "=================================="

echo "Symmetric Key Sizes:"
echo "  1) 128 bits (16 bytes)"
echo "  2) 256 bits (32 bytes)"
keysize_choice=$(read_input "Choose key size (1 or 2)" "2")

case "$keysize_choice" in
    1)
        KEYSIZE="128"
        echo "✓ Selected: 128-bit keys"
        ;;
    2)
        KEYSIZE="256"
        echo "✓ Selected: 256-bit keys"
        ;;
    *)
        KEYSIZE="256"
        echo "✓ Defaulting to 256-bit keys"
        ;;
esac

echo ""

# ===== PHASE 5: Update Server Configuration =====
echo "[PHASE 5] Updating Configuration Files"
echo "======================================"

SERVER_CONFIG="$SERVER_DIR/Cryptoconfig.conf"

cat > "$SERVER_CONFIG" << EOF
# RTSSP Cryptographic Configuration
# Generated by setup.sh on $(date)

# Protocol Mode (RTSSP or RTSSP-SHP)
mode=$MODE

# Cipher Algorithm
cipher.algorithm=$CIPHER

# HMAC Algorithm
hmac.algorithm=$HMAC

# Key size in bits
cipher.keysize=$KEYSIZE

# IV size in bits (128 = 16 bytes for AES)
cipher.ivsize=128

# === Part 2 (SHP) Settings ===
# Server keystore path and credentials
server.keystore.path=server.jks
server.keystore.password=serverpass
server.keystore.alias=server
server.keystore.keypass=serverpass

# Server truststore
server.truststore.path=server.truststore
server.truststore.password=serverpass

# Proxy listening address for handshake
handshake.proxy.host=localhost
handshake.proxy.port=8888
EOF

echo "✓ Updated: $SERVER_CONFIG"
echo "  - Mode: $MODE"
echo "  - Cipher: $CIPHER"
echo "  - Key Size: $KEYSIZE bits"

echo ""

# ===== PHASE 6: Regenerate certificates if SHP mode =====
if [ "$MODE" = "RTSSP-SHP" ]; then
    echo "[PHASE 6] Certificate Generation (SHP Mode)"
    echo "=========================================="
    
    if ask_yes_no "Regenerate certificates for SHP handshake?"; then
        echo "Generating server certificate..."
        cd "$SERVER_DIR"
        rm -f server.jks server.truststore server.cer
        keytool -genkeypair -alias server \
            -keyalg EC -groupname secp256r1 \
            -keystore server.jks \
            -storepass serverpass -keypass serverpass \
            -validity 365 \
            -dname "CN=StreamServer,OU=CA,O=Lab,C=PT" \
            -noprompt 2>/dev/null
        echo "✓ Server keystore created"

        echo "Generating proxy certificate..."
        cd "$PROXY_DIR"
        rm -f proxy.jks proxy.truststore proxy.cer
        keytool -genkeypair -alias proxy \
            -keyalg EC -groupname secp256r1 \
            -keystore proxy.jks \
            -storepass proxypass -keypass proxypass \
            -validity 365 \
            -dname "CN=StreamProxy,OU=CA,O=Lab,C=PT" \
            -noprompt 2>/dev/null
        echo "✓ Proxy keystore created"

        echo "Exchanging certificates..."
        cd "$SERVER_DIR"
        keytool -export -alias server -keystore server.jks \
            -storepass serverpass -file server.cer -noprompt 2>/dev/null

        cd "$PROXY_DIR"
        keytool -export -alias proxy -keystore proxy.jks \
            -storepass proxypass -file proxy.cer -noprompt 2>/dev/null

        keytool -import -alias server -file "$SERVER_DIR/server.cer" \
            -keystore proxy.truststore -storepass proxypass -noprompt 2>/dev/null

        cd "$SERVER_DIR"
        keytool -import -alias proxy -file "$PROXY_DIR/proxy.cer" \
            -keystore server.truststore -storepass serverpass -noprompt 2>/dev/null

        echo "✓ Truststores created"
        echo "✓ Certificates exchanged"
    fi
    
    echo ""
fi

# ===== PHASE 7: Compile =====
echo "[PHASE 7] Compilation"
echo "===================="

if ask_yes_no "Compile Java files now?"; then
    echo "Compiling server..."
    cd "$SERVER_DIR"
    javac *.java 2>&1 | grep -i error || echo "✓ Server compiled successfully"

    echo "Compiling proxy..."
    cd "$PROXY_DIR"
    javac *.java 2>&1 | grep -i error || echo "✓ Proxy compiled successfully"
fi

echo ""

# ===== Summary =====
echo "==============================================="
echo "  Configuration Complete!"
echo "==============================================="
echo ""
echo "Configuration Summary:"
echo "  Protocol Mode:  $MODE"
echo "  Cipher:         $CIPHER"
echo "  Key Size:       $KEYSIZE bits"
echo "  Server Config:  $SERVER_CONFIG"
echo ""

if [ "$MODE" = "RTSSP" ]; then
    echo "To run Part 1 (RTSSP):"
    echo "  Terminal 1: cd hjStreamServer && java hjStreamServer movies/movie.dat localhost 5000"
    echo "  Terminal 2: cd hjUDPproxy && java hjUDPproxy"
else
    echo "To run Part 2 (RTSSP-SHP):"
    echo "  Terminal 1: cd hjStreamServer && java hjStreamServer movies/movie.dat localhost 5000"
    echo "  Terminal 2: cd hjUDPproxy && java hjUDPproxy"
    echo "  Note: Server waits for handshake on port 8888"
fi

echo ""
echo "==============================================="
